# src/OC/PlatformBundle/Resources/config/routing.yml

oc_platform_home:
    path:      /
    defaults: { _controller: OCPlatformBundle:Advert:index }

oc_platform_view:
    path:      /advert/{id}
    defaults: { _controller: OCPlatformBundle:Advert:view }



    # src/OC/PlatformBundle/Resources/config/routing.yml

oc_platform_view_slug:
    path:      /{year}/{slug}.{format}
    defaults: { _controller: OCPlatformBundle:Advert:viewSlug}