# src/OC/PlatformBundle/Resources/config/services.yml

services:
  oc_platform.antispam:
    class: OC\PlatformBundle\Antispam\OCAntispam
    arguments:
    - "@mailer" //service
    - %locale% // variable
    - 50 // une constante

